# Generated by Django 5.0 on 2024-09-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_department_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
